# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CFD1D4
background         #001124
cursor             #09847F

active_tab_foreground     #001124
active_tab_background     #CFD1D4
inactive_tab_foreground   #CFD1D4
inactive_tab_background   #001124

active_border_color   #CFD1D4
inactive_border_color #001124
bell_border_color     #19BEA4

color0      #9B9DA2
color1		#19BEA4
color2		#01A999
color3		#01A397
color4		#0C7F4C
color5		#027175
color6		#006E58
color7		#0F7263
color8		#17B199
color9		#21FDDB
color10		#01E1CD
color11		#01D9CA
color12		#10A966
color13		#03969C
color14		#019276
color15		#88F6E5
