# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(18131B)
$foreground = rgb(FDE4F7)
$color0 = rgb(3F3A43)
$color1 = rgb(613459)
$color2 = rgb(703767)
$color3 = rgb(773A6B)
$color4 = rgb(A5586B)
$color5 = rgb(A95B6B)
$color6 = rgb(BC85AF)
$color7 = rgb(F4D0EC)
$color8 = rgb(AB91A5)
$color9 = rgb(824576)
$color10 = rgb(964A89)
$color11 = rgb(9F4D8F)
$color12 = rgb(DC758F)
$color13 = rgb(E1798F)
$color14 = rgb(FAB1E9)
$color15 = rgb(F4D0EC)
